# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdd3bee24d11e14a7e32e22968cc2cfa7c9efd69ad55121d11a8b7eabb392fda55dfccc1a3068d3df9db510d6f6fbe1f288aeebe7e985202eb88b9b9ee0b9bb7

test:
  secret_key_base: 9741d66f2096b8254fc49bfd7446b1aaf958dd52c72ff84fc8856d5d6f3d035485e13a55f804a54152ca9d5e8f8d228ca2f46c43c04bab1410b951567df5265d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
